### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by GilbertGobbels** [TerraBite-Development-Team/TerraBite#2]
Y'know, a reference to GAB or credit to me for writing your privacy policy would be nice ;)

**Comment by KingDGrizzle** [comment]
And, because I'd like to remove all and every `but we did it first cases`

![image](https://hypesquad.dabbit-pri.me/eaa6eb.png)

**Comment by oskikiboy** [comment]
I'll get to it.

**Comment by oskikiboy** [comment]
fixed
